### ISSUE TITLE
Enable TLS 1.3

### ISSUE THREAD

**Issue by LionelJouin** [Nordix/Meridio#117]
Currently TLS 1.2 is used.

The Spire API (grpccredentials.MTLSServerCredentials, grpccredentials.MTLSClientCredentials) we are using to create the TransportCredentials [doesn't support TLS version selection](https://github.com/spiffe/spire/issues/1976).

We should modify the tls config as it is done in this example:
https://github.com/projectcontour/contour/blob/011fe4023796769e8762587f7e7136c432549720/cmd/contour/servecontext.go#L195
https://github.com/projectcontour/contour/blob/011fe4023796769e8762587f7e7136c432549720/cmd/contour/servecontext.go#L156

**Comment by giangtraan** [comment]
Meridio supports both TLS 1.2 and TLS 1.3, with TLS 1.3 being preferred over TLS 1.2. 
There is no need as of now to enforce TLS 1.3 only.
