### ISSUE TITLE
Meridio first release

### ISSUE THREAD

**Issue by johlj** [Nordix/Meridio#122]
Meridio first release and procedure documentation

**Comment by mandydydy** [comment]
| Operator go.mod Referring main product release version | Main product go.mod referring operator | Operator release note referring main release version | Submodule relation
-- | -- | -- | -- | --
Argo cd | yes | no | yes | none
Kafka(banzai) | No(different language) | no | yes | none
Kafka(strimzi) | Yes(same language) | no | yes | none
datadog | No(shared dependencies) | Hash version | No | none
grafana | No | no | yes | none
