### ISSUE TITLE
Verify and if not present add encryption for the operator control plane traffic

### ISSUE THREAD

**Issue by johlj** [Nordix/Meridio#124]
Verify and if not present add encryption for the operator control plane traffic

**Comment by mandydydy** [comment]
1. Get, list, watch, create, update etc of K8S native and customed resources in the pod:
Kubernetes expects that all API communication in the cluster is encrypted by default with TLS Validating webhook. Pods does the above actions with authentication by service account and authorization by rbac(roles and role bindings) 
https://kubernetes.io/docs/tasks/administer-cluster/securing-a-cluster/#controlling-access-to-the-kubernetes-api  
2. Webhooks:
The caBundle is used to verify the tls connection between the webhooks & kube API. If caBundle is not specified, CA of the system trust root will be used. 
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#contacting-the-webhook  
3. The encrypted communication between meridio and nsm is covered through spiffe.
