### ISSUE TITLE
Use fwmarks in Flow rules to pin-point stream

### ISSUE THREAD

**Issue by zolug** [Nordix/Meridio#126]
Note: Might not be valid once upgraded to nfqlb with Stream Select support

nfqlb is supposed to drop received packets if no active targets are known to it.
However due to a bug this wasn't the case up until nfqlb v0.5.0.

Due to the cascade nature of Flow rules the above fix affects Meridio as well:
Currently Flow rules have a nfqueue statement directing the matching packet to an nfqlb instance.
In case of overlapping Flow rules the packets fate should be decided by the last matching Flow rule, meaning the Flow rule with the highest priority must prevail. However since rules with lower priority are visited first if one of these "earlier" nfqlb instances have no active targets registered, the packet should end up being dropped by nfqlb.

To overcome this problem, and to also avoide visiting nfqlb multiple times for a packet let's change the Flow rules to:
1., mark packets with an fwmark value unique to the stream (instead of using the queue statement)
Note: the nfqueue num values could be used as fwmark value as well
2., add a new "stream-selector" chain with INT_MAX -1 priority to PREROUTING, where each stream should add a rule that would direct packets to the respective nfqlb instance upon matching the right fwmark. 

example:

chain flow-a-stream-a {
   type filter hook prerouting priority filter; policy accept;
   meta l4proto @flow-a-stream-a-protocol ip saddr @flow-a-stream-a-src-ipv4 ip daddr @flow-a-stream-a-dst-ipv4 th dport @flow-a-stream-a-dst-port th sport @flow-a-stream-a-src-port mark set 1
}

chain flow-b-stream-b {
   type filter hook prerouting priority filter + 5; policy accept;
   meta l4proto @flow-b-stream-b-protocol ip saddr @flow-b-stream-b-src-ipv4 ip daddr @flow-b-stream-b-dst-ipv4 th dport @flow-b-stream-b-dst-port th sport @flow-b-stream-b-src-port mark set 2
}

chain stream-selector {
   type filter hook prerouting priority INT_MAX - 1 ; policy accept;
   meta mark 1 queue num 1
   meta mark 2 queue num 2
}

**Comment by uablrek** [comment]
Obsoleted by `nfqlb flowlb`.
