### ISSUE TITLE
Unclear for-loop and busy-loop

### ISSUE THREAD

**Issue by uablrek** [Nordix/Meridio#154]
In;

https://github.com/Nordix/Meridio/blob/865aecc108f97c8ca28607b07b59cbb1cc053966/pkg/ipam/server.go#L89-L101

A (nil,nil) return from `trench.GetConduit()` seem to be valid (not found). But that creates an infinite loop (I got it, caused by a config fault). If (nil,nil) is detected and breaks the loop, you will never get more than 1 (one) loop.

**Comment by uablrek** [comment]
The "ctx.Err() != nil" will eventually break the loop but after quite many loops (I added a debug printout)

**Comment by LionelJouin** [comment]
The subnet creation is triggered by the Meridio configuration. The IPAM is creating a new subnet for every conduits in the trench, so if a proxy requests a subnet for a non existing conduit, the IPAM has to wait until one is created (or until the ctx expired (`ctx.Err() != nil`)). This is not the best way to implement it, and it misses comments and documentation, sorry for that.

**Comment by uablrek** [comment]
Then add a `time.Sleep()`. A busy-loop is never good, even a short one.
