### ISSUE TITLE
Improve documentation and directory structure

### ISSUE THREAD

**Issue by uablrek** [Nordix/Meridio#161]
The documentation must be improved. Most urgent is the `readme.md` on top-level. It should give an overview of what Meridio is and where it is used, depenceny of NSM and such things, not describe the build process for instance.

The `demo/` directory should be removed and its contents moved to more appropriate places. It is a survivior from the early days and has become some general trash can for all kind of stuff.

The `overview` assumes that the reader is already familiar with the purpose and backgound of Meridio. That said, IMO the overview is the best documentation in Meridio currently. I have frequently returned to the diagram for instance

This is not about the `go` code structure, which is basically fine.

**Comment by LionelJouin** [comment]
I agree the documentation must be updated and improved, but I think the `demo` directory has been maintained correctly with only relevant files (at least for Kind, not sure for xcluster). It contains all information on how to deploy a simple Meridio example. 

However, I think `/examples/target` should be re-worked, we should create a new go.mod (to keep Meridio and the example clearly separated for tests, presentations...) and we should move the code in `test/applications/target-client` to `/examples/target`.
