### ISSUE TITLE
Expose max number of target as env variable

### ISSUE THREAD

**Issue by LionelJouin** [Nordix/Meridio#167]
Currently the maximum number of targets if 100, this also means, for example, if a target opens 100 streams, no more identifier will be available.

- [ ] TAPA
- [ ] Load-balancer

https://github.com/Nordix/Meridio/blob/master/pkg/ambassador/tap/stream/consts.go#L22
https://github.com/Nordix/Meridio/blob/master/cmd/load-balancer/main.go#L58

**Comment by uablrek** [comment]
This should *really* be a stream property, not an env variable. E.g in the proposed sctp solution all sctp streams will have just one target, and there will be many of them (up to 256). The current default N=100 gives;
```
# ls -hl /dev/shm
total 3.9M
-rw------- 1 root root   72 Feb 18 07:55 ftshm
-rw------- 1 root root 3.9M Feb 18 07:55 tshm-stream1
```
The allocated space is of O(N^2) so if just one stream needs 1000 targets and this is set with an environment variable to the then *all* streams, including the sctp ones with just one target, will consume an *awful* ammount of mem!

**Comment by LionelJouin** [comment]
If so, an offset should be added in the stream too, the NSP API and configmap would require modifications. 

The current implementation is a bit specific on this, all streams are sharing the same identifier range, so if a target registered with identifier 50 on stream-a, the targets are not allowed to choose the same identifier, even to register other stream.

**Comment by uablrek** [comment]
I don't know the implementation details, but;
```
> nfqlb init --N=1000 --M=993997
> ls -lh /dev/shm
total 2.0G
-rw------- 1 uablrek lgekman 2.0G Feb 18 10:00 nfqlb
```
Times 256! I don't think this will be acceptable.

**Comment by uablrek** [comment]
But a _default_ N may be settable with an environment variable.

**Comment by uablrek** [comment]
Obsoleted by https://github.com/Nordix/Meridio/issues/174
