### ISSUE TITLE
proxy; locally generated ICMP Unreachable routed into default net

### ISSUE THREAD

**Issue by zolug** [Nordix/Meridio#177]
Proxies fail to route locally generated ICMP Fragmentation Needed msg to originating Target.
(In fact the reply will be sent to the default network.)

Background:
A Target/Ambassador connects the Proxy located on the same worker, thus the MTU of the NSM interface between them is 9000.
However the proxy might need to forward traffic to a Load-Balancer located on a different worker, in which case NSM connects them using VxLAN where the interface MTU is set to 1500 bytes.

Thus in case of IPv4 the proxy might need to generate an ICMP Unreachable (Frag Needed) reply upon a msg (originating from a Target) that does not fit the next hop interface (and fragmentation is not allowed).
IPv6 is also affected.

Probably the same MTU should be used by NSM irrespective of the xconnect protocol. Thus avoiding the need for sophisticated routing logic to return locally generated ICMP Unreachable packets to the originator.

**Comment by uablrek** [comment]
Don't do that.

**Comment by zolug** [comment]
> Don't do that. Take care of MTU at the edges, FE and target

Unfortunately on the Target side that would either mean additional privileges, or NSM's policy based rule feature should be extended.

For now, an environment var had been introduced to the proxy. That will be taken into consideration by the proxy NSE and NSC (responsible "connecting" Targets and LBs via NSM xconnects) to set the configured MTU. While NSM will apply the requested MTU considering the underlying network infrastucture and the chosen NSM connect mechanism if possible.
https://github.com/Nordix/Meridio/pull/223
