### ISSUE TITLE
Logging improvement needed

### ISSUE THREAD

**Issue by giangtraan** [Nordix/Meridio#253]
Log produced by 

- [ ] IPAM, 
- [ ] NSP and 
- [ ] TAPA need improvement to give more information for troubleshooting.

**Comment by uablrek** [comment]
@giangtraan Three sub-programs are specially mentioned in this issue. I assume there have been problems that were hard to find in these sub-programs. To be able to _improve_ logging (not only make it structured) I would like to know what those problems were.
