### ISSUE TITLE
Meridio traffic flows support

### ISSUE THREAD

**Issue by johlj** [Nordix/Meridio#31]

**Comment by tedlean** [comment]
The support for flows in for the most to be included in the FE function block.  Incoming traffic is to be classified into flows matching preconfigured 5-tuples.  Traffic that do not match any flows should be dropped silently. (We might consider adding a PM counter for dropped packages at some point. Maybe std. Linux counters will do.)
The flows are configuration-wise mapped to a stream which again is lead into a conduit.  The conduit reflects a (physical) traffic path through the cluster where the traffic is to pass a chain of network services.
