### ISSUE TITLE
Meridio traffic streams support

### ISSUE THREAD

**Issue by johlj** [Nordix/Meridio#32]

**Comment by tedlean** [comment]
Stream support is mostly to be implemented as part of the LB function block. Traffic is classified into a flow which is mapped to a stream. On the LB level each stream is to be handled separately. Some target pod might sign up to receive traffic from one stream while others might sign up for another stream and some for both etc. 
This means that there in principle is to be a separate LB function per stream.  Notice that the flow classification and stream mapping done in the FE function block has to be repeated in the LB as the traffic is not tagged by the FE in any way.
