### ISSUE TITLE
Old NSM interface in LB might cause traffic disturbance

### ISSUE THREAD

**Issue by zolug** [Nordix/Meridio#392]
**Describe the bug**
In case a Proxy is terminated abruptly it has no chance to Close() the NSM connections it maintains towards LBs.

In such cases NSM provides a timeout mechanism (governed by MaxTokenLifetime) to issue a Close() on such connections. However, occasionally these NSM originated Close() calls fail, thus the related NSM interface is not removed from the LB side.
The failure seem to be returned by some authorize nsm chain component and complains about ```rpc error: code = PermissionDenied desc = no sufficient privileges```.

If later a new NSM connection gets established toward the affected LB for which the IP subnet matches the previously stuck interface's subnet, it might cause forwarding issues. That's because the kernel might try to send packets through the old dangling interface.

Solution proposal in Meridio:
In an LB normally there should be only 1 interface for a particular subnet which connects it to a proxy "owning" the subnet.
Thus whenever a new NSM connection is established towards an LB it could check if there are any other interfaces in the POD that might share the same subnet. If there are, their state should be set to DOWN.

Note: The ```PermissionDenied``` error might occasionally be returned even if the Proxy called Close() for an NSM connection. In which case the associated interface ends up stuck in the Proxy possibly causing confusion (even though the interface should have been removed from the bridge and from the PBRs). We could also set the state of such interfaces to Down upon Close.

**To Reproduce**
???
So far has been noticed after reboots of workers hosting Proxies.
Might be possible to 

**Expected behavior**
Old interface should not get stuck. Otherwise the timeout mechanism NSM offers doesn't provide satisfactory recovery time.

**Context**
 - Network Service Mesh: v1.6.1
 - Meridio: v1.0.1
 

**Logs**
Add logs here.

**Comment by uablrek** [comment]
FYI, like 100% reproducible in xcluster. Makes it easy to test this PR...

**Comment by uablrek** [comment]
Fixed by https://github.com/Nordix/Meridio/pull/404
