### ISSUE TITLE
The MAC-address for the IP-address of the Proxy is changed sometimes.

### ISSUE THREAD

**Issue by tedlean** [Nordix/Meridio#471]
**Describe the bug**

The IP-address of the proxy used as nexthop for outgoing traffic from the target pods sits on the Bridge0 interface. 
The MAC-address of this interface can be changed without restarting the proxy. 

It seems that the bridge0 interface "borrows" the MAC from an LB-FE tunnel interface.
If the LB-FE is restarted and the NSM-link is renewed the bridge0 will also get a new MAC.

This is bad for the target pod, which already has the old MAC -address in the cache. 
Outgoing traffic will be blackholed until the ARP cache is renewed.

**To Reproduce**
1. ...
2. ...

**Expected behavior**
Best option: ensure that the bridge0 has a persistent MAC-address, despite restarting of LB-FE pods.
Second best option: Send a GARP message if the MAC-address has been changed.

**Context**
 - Kernel: [e.g. 5.15.43]
 - Kubernetes: [e.g. v1.24.1]
 - Spire: [e.g. v1.3.0]
 - Network Service Mesh: [e.g. v1.3.1]
 - Meridio: [e.g. v0.5.1]
 ...

**Logs**
----- ip on nvip on POD eric-tm-senp-nvip-proxy-lb-fe-a-ff74z Tue Oct 17 03:11:48 UTC 2023 ---
5: bridge0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1396 qdisc noqueue state UP group default
    link/ether 02:fe:b5:74:34:03 brd ff:ff:ff:ff:ff:ff
9: lb-fe-a.tr-87e9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1396 qdisc mq master bridge0 state UNKNOWN group default qlen 1000
    link/ether 02:fe:b5:74:34:03 brd ff:ff:ff:ff:ff:ff

 
----- ip on nvip on POD eric-tm-senp-nvip-proxy-lb-fe-a-ff74z Tue Oct 17 03:11:58 UTC 2023 ---
5: bridge0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1396 qdisc noqueue state UP mode DEFAULT group default
    link/ether 02:fe:53:65:6d:ab brd ff:ff:ff:ff:ff:ff promiscuity 0 minmtu 68 maxmtu 65535
10: lb-fe-a.tr-95b8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1396 qdisc mq master bridge0 state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 02:fe:53:65:6d:ab brd ff:ff:ff:ff:ff:ff promiscuity 1 minmtu 68 maxmtu 65521

**Comment by dezenxi** [comment]
According to https://superuser.com/questions/1720967/how-does-linux-determine-the-default-mac-address-of-a-bridge-device, it seems that the MAC of bridge0 is inherited from its attached interfaces. And the MAC will be changed when there is remove/re-add interface at LB-frontend restart

**Comment by LionelJouin** [comment]
Solved with https://github.com/Nordix/Meridio/pull/473
