### ISSUE TITLE
Traffic load-balancing issue on a target removal

### ISSUE THREAD

**Issue by LionelJouin** [Nordix/Meridio#55]
#### What happened:
On a target removal (scale-in or disconnection of a target from a trench), the traffic is not received by all remaining targets. For instance, if there are 4 targets connected to a trench and receiving the traffic correctly, if one is removed, the traffic might reach only 2 targets instead of 3.

This bug is happening rarely and randomly.

This could also happen when the e2e tests are running which makes some test cases failing.

```
STEP: Disconnecting the target from a trench
• Failure [10.618 seconds]
Target
/Meridio/test/e2e/target_test.go:30
  With one trench (trench-a) deployed in namespace red containing 2 VIP addresses (20.0.0.1:5000, [2000::1]:5000) and 4 target pods running ctraffic
  /Meridio/test/e2e/target_test.go:52
    should be possible for a target to disconnect from a trench and connect to it again [It]
    /Meridio/test/e2e/target_test.go:71

    Expected
        <int>: 2
    to equal
        <int>: 3

    /Meridio/test/e2e/target_test.go:78
```

#### What you expected to happen:
The traffic should reach and be load-balancer among all remaining targets.

#### How to reproduce it (as minimally and precisely as possible):
Deploy Meridio with 2 trenches, and 4 targets in each trench.

To reproduce it, we can or run the e2e tests:
```
make e2e
```

Or disconnect a target manually:
On a target:
```
./target-client disconnect -ns load-balancer -t trench-a
```

On the traffic generator host:
```
ctraffic -address 20.0.0.1:5000 -nconn 400 -rate 100 -monitor -stats all > v4traffic.json
ctraffic -analyze hosts -stat_file v4traffic.json
```

#### Environment:
- Kind (1 Master and 2 Workers)
- Kubernetes 1.20.1
- NSM 1.0
- Meridio - e570a21a215103b74e2591e689bf1b395d096a5c

**Comment by uablrek** [comment]
The re-try problem solved. The large number (relatively) saturated the conntrack table. A `conntrack -F` before the `mconnects` made the re-tries disappear. Ran 30 iterations without any problems at all. Closing the issue
