### ISSUE TITLE
Operator support for VIP ranges

### ISSUE THREAD

**Issue by johlj** [Nordix/Meridio#65]
Add support for setting VIP ranges with the operator

**Comment by mandydydy** [comment]
https://github.com/Nordix/Meridio-Operator/pull/22

**Comment by mandydydy** [comment]
Seems vips need more validation:
vip address like 10.0.0.1/28 is not allowed, with make fe container to crash

Reading configuration from /etc/bird/bird-fe-meridio.conf
/etc/bird/bird-fe-meridio.conf:50:17 Invalid IPv4 prefix 10.0.0.1/28, maybe you wanted 10.0.0.0/28
